# Phiên bản cấu hình docker-compose
version: "3.8"

services:
  # Cấu hình cho dịch vụ Backend
  backend:
    build:
      context: ./backend # Chỉ đường dẫn đến thư mục chứa Dockerfile của backend
    # Tên Image dùng để quản lý và đẩy lên Docker Hub
    image: hquang123/booking-app-backend:latest
    ports:
      - "5000:5000" # Máy thật truy cập 5000 -> Container cổng 5000
    env_file:
      - ./backend/.env # Nạp toàn bộ biến môi trường từ file .env vào server
    environment:
      - NODE_ENV=production # Chạy ở chế độ production

  # Cấu hình cho dịch vụ Frontend
  frontend:
    build:
      context: ./frontend/my-app # Chỉ đường dẫn đến Dockerfile của frontend
    # Tên Image dùng để quản lý và đẩy lên Docker Hub
    image: hquang123/booking-app-frontend:latest
    ports:
      - "80:80" # Truy cập web qua cổng 80 (cổng mặc định HTTP)
    depends_on:
      - backend # Backend phải khởi động trước thì Frontend mới bắt đầu chạy
